website/routes/web.php
<?php

use App\Http\Controllers\BinController;
use App\Http\Controllers\BinLogController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home');
})->name('home');

Route::group(["middleware" => "auth"], function () {
    Route::resource("/dashboard", DashboardController::class)
        ->names('dashboard');
    Route::resource("/bin", BinController::class)
        ->names('bin');
    Route::resource("/bin-logs", BinLogController::class)
        ->names('bin-log');
    Route::resource("/notification", NotificationController::class)
        ->names('notify');

    Route::get("/my-profile/{id}", [UserController::class, 'show'])->name('profile');

    Route::resource("/user", UserController::class)
        ->names('user');
});

require __DIR__ . '/auth.php';

website/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'date',
        'updated_at' => 'date',
        'email_verified_at' => 'datetime',
    ];
}

website/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use DataTables;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = User::latest()->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('created_on', function ($row) {
                    if ($row->created_at) {
                        return $row->created_at->diffForHumans();
                    }

                    return '--';
                })
                ->addColumn('verified', function ($row) {
                    if ($row->email_verified_at) {
                        return '<span class="badge bg-success">Yes</span>';
                    }

                    return '<span class="badge bg-danger">No</span>';
                })
                ->addColumn('updated_on', function ($row) {
                    if ($row->updated_at) {
                        return $row->updated_at->diffForHumans();
                    }

                    return '--';
                })
                ->addColumn('action', function ($row) {
                    return '<a href="' . route("user.show", $row->id) . '" class="btn btn-success btn-sm"> <i class="fa fa-view"></i> View</a>';
                })
                ->rawColumns(['action', 'verified'])
                ->make(true);
        }

        return view('pages.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('pages.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        return view('pages.user.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        //
    }
}

website/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * The alert active.
     *
     * @var string
     */
    public $active;

    /**
     * The alert title.
     *
     * @var string
     */
    public $title;

    /**
     * The alert content class.
     *
     * @var string
     */
    public $areawrapper;

    /**
     * Create the component instance.
     *
     * @param  string  $active
     * @param  string  $title
     * @param  string  $areawrapper
     * @return void
     */
    public function __construct($active = null, $title = null, $areawrapper = false)
    {
        $this->active = $active;
        $this->title = $title;
        $this->areawrapper = $areawrapper;
    }
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

website/resources/views/pages/user/create.blade.php
<x-app-layout title="Users" :active="route('user.index')">		
	<div class="container-fluid p-0">

		<h1 class="h3 mb-3">
			Create User
			<a href="{{ route('user.index') }}" class="btn btn-primary float-end">All Users</a>
		</h1>

	</div>
</x-app-layout>

website/resources/views/pages/user/index.blade.php
<x-app-layout title="Users" :active="route('user.index')">		
	<div class="container-fluid p-0">

		<h1 class="h3 mb-3">
			System Users
			<a href="{{ route('user.create') }}" class="btn btn-primary float-end">Add User</a>
		</h1>

		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<table class="table table-striped" id="users-table" style="width:100%">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Email</th>
									<th>Verified</th>
									<th>Created At</th>
									<th>Updated At</th>
								</tr>
							</thead>
							<tbody></tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	
	</div>

	<script type="text/javascript">
		$(function () {
			const table = $('#users-table').DataTable({
				processing: true,
				serverSide: true,
				ajax: "{{ route('user.index') }}",
				columns: [
					{data: 'DT_RowIndex', name: 'DT_RowIndex'},
					{data: 'name', name: 'name'},
					{data: 'email', name: 'email'},
					{data: 'verified', name: 'verified'},
					{data: 'created_on', name: 'created_on'},
					{data: 'updated_on', name: 'updated_on'},
				]
			});
		});
	</script>

</x-app-layout>

website/resources/views/pages/user/show.blade.php
<x-app-layout title="My Profile" :active="route('profile', Auth::id(), )">
				
	<div class="container-fluid p-0">

		<h1 class="h3 mb-3">
			My Profile
		</h1>
	
		<div class="col-12 col-xl-6">
			<div class="card">
				<div class="card-body">
					<form action="{{ route("user.store") }}" method="POST">
						@csrf
						@method('POST')

						<div class="mb-3">
							<label class="form-label">Full Name</label>
							<input type="text" class="form-control" placeholder="Full name">
						</div>
						<div class="mb-3">
							<label class="form-label">Email address</label>
							<input type="email" class="form-control" placeholder="Email">
						</div>
						<button type="submit" class="btn btn-primary">
							Update
						</button>
					</form>
				</div>
			</div>
		</div>

		<div class="col-md-6 col-12">
			<div class="card">
				<div class="card-header">
					<h5 class="card-title">Change Password</h5>
				</div>
				<div class="card-body">
					<form action="{{ route('user.update', auth()->id()) }}" method="POST">
						@csrf
						@method('post')

						<div class="mb-3">
							<label class="form-label" for="old-password">Old Password</label>
							<input type="password" class="form-control" id="old-password" placeholder="Current password">
						</div>

						<div class="mb-3">
							<label class="form-label" for="new-password">New Password</label>
							<input type="password" class="form-control" id="new-password" placeholder="New Password">
						</div>

						<div class="mb-3">
							<label class="form-label" for="confirm-password">Confirm Password</label>
							<input type="password" class="form-control" id="confirm-password" placeholder="Confirm Password">
						</div>

						<div class="mb-3">
							<button type="submit" class="btn btn-primary mb-2">
								Change
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</x-app-layout>