website/routes/web.php
<?php

use App\Http\Controllers\BinController;
use App\Http\Controllers\BinLogController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home');
})->name('home');

Route::group(["middleware" => "auth"], function () {
    Route::resource("/dashboard", DashboardController::class)
        ->names('dashboard');
    Route::resource("/bin", BinController::class)
        ->names('bin');
    Route::resource("/bin-logs", BinLogController::class)
        ->names('bin-log');
    Route::resource("/notification", NotificationController::class)
        ->names('notify');

    Route::get("/my-profile/{id}", [UserController::class, 'show'])->name('profile');

    Route::resource("/user", UserController::class)
        ->names('user');
});

require __DIR__ . '/auth.php';

website/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'GMS') }}</title>

        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">

        <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">

        <!-- Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

        <script src="{{ asset('assets/js/app.js') }}" defer></script>
    </head>
    <body>
       	<div class="wrapper">
            {{-- sibe bar --}}
            @include('layouts.navigation', [
                    'isActive' => $active ?? route('dashboard.index'),
                ])

            <div class="main">
                
                @include('layouts.top-nav')

                <!-- Page Content -->
                <main class="content">
                    {{ $slot }}
                </main>

                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row text-muted">
                            <div class="col-6 text-start">
                                <p class="mb-0">
                                    <a class="text-muted" href="javascript:void(0)"><strong>Garbage</strong></a> - <a class="text-muted" href="javascript:void(0)"><strong> Monitoring System</strong></a> &copy; All rights reserved.
                                </p>
                            </div>
                        </div>
                    </div>
                </footer>

            </div>
        </div>
    </body>
</html>

website/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('assets/js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="form-signin">
            {{ $slot }}
        </div>
    </body>
</html>

website/resources/views/layouts/navigation.blade.php
<nav id="sidebar" class="sidebar js-sidebar">
	<div class="sidebar-content js-simplebar">
		<a class="sidebar-brand" href="{{ route('home') }}">
			<span class="align-middle">
				GM System
			</span>
		</a>

		<ul class="sidebar-nav">

			<li class="sidebar-item @if ($isActive==route('dashboard.index'))
				{{ __('active') }}
			@endif">
				<a class="sidebar-link" href="{{ route('dashboard.index') }}">
					<i class="align-middle" data-feather="home"></i>
					<span class="align-middle">Dashboard</span>
				</a>
			</li>

			<li class="sidebar-item @if ($isActive==route('bin-log.index'))
				{{ __('active') }}
			@endif">
				<a class="sidebar-link" href="{{ route('bin-log.index') }}">
					<i class="align-middle" data-feather="list"></i>
					<span class="align-middle">Bin Logs</span>
				</a>
			</li>

			<li class="sidebar-item @if ($isActive==route('bin.index'))
				{{ __('active') }}
			@endif">
				<a class="sidebar-link" href="{{ route('bin.index') }}">
					<i class="align-middle" data-feather="trash"></i>
					<span class="align-middle">Bins</span>
				</a>
			</li>

			<li class="sidebar-item @if ($isActive==route('notify.index'))
				{{ __('active') }}
			@endif">
				<a class="sidebar-link" href="{{ route('notify.index') }}">
					<i class="align-middle" data-feather="bell"></i>
					<span class="align-middle">Notifications</span>
				</a>
			</li>

			<li class="sidebar-item @if ($isActive==route('user.index'))
				{{ __('active') }}
			@endif">
				<a class="sidebar-link" href="{{ route('user.index') }}">
					<i class="align-middle" data-feather="users"></i>
					<span class="align-middle">Users</span>
				</a>
			</li>

			<li class="sidebar-item @if ($isActive==route('profile', auth()->id()))
				{{ __('active') }}
			@endif">
				<a class="sidebar-link" href="{{ route('profile', auth()->id()) }}">
					<i class="align-middle" data-feather="user"></i>
					<span class="align-middle">My Profile</span>
				</a>
			</li>

		</ul>

		<div class="sidebar-cta">
			<div class="sidebar-cta-content">
				<div class="d-grid">
					<a href="{{ route('home') }}" class="btn btn-primary">Go to Home</a>
				</div>
			</div>
		</div>

	</div>
</nav>

website/resources/views/layouts/top-nav.blade.php
<nav class="navbar navbar-expand navbar-light navbar-bg">
	<a class="sidebar-toggle js-sidebar-toggle">
		<i class="hamburger align-self-center"></i>
	</a>

	<div class="navbar-collapse collapse">
		<ul class="navbar-nav navbar-align">
			<li class="nav-item dropdown">
				<a class="nav-icon dropdown-toggle" href="#" id="bin-alerts" data-bs-toggle="dropdown">
					<div class="position-relative">
						<i class="align-middle" data-feather="bell"></i>
						<span class="indicator">0</span>
					</div>
				</a>
				<div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="bin-alerts">
					<div class="dropdown-menu-header">
						0 New Notifications
					</div>
					<div class="list-group">
						<a href="#" class="list-group-item">
							<div class="row g-0 align-items-center">
								<div class="col-2">
									<i class="text-danger" data-feather="alert-circle"></i>
								</div>
								<div class="col-10">
									<div class="text-dark">Update completed</div>
									<div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
									<div class="text-muted small mt-1">30m ago</div>
								</div>
							</div>
						</a>
					</div>
					<div class="dropdown-menu-footer">
						<a href="#" class="text-muted">Show all notifications</a>
					</div>
				</div>
			</li>

			<li class="nav-item dropdown">
				<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
					<i class="align-middle" data-feather="settings"></i>
				</a>

				<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
					<img src="{{ asset('assets/img/avatars/avatar.jpg') }}" class="avatar img-fluid rounded me-1" alt="{{ Auth::user()->name }}" />
					<span class="text-dark text-capitalize">{{ Auth::user()->name }}</span>
				</a>

				<div class="dropdown-menu dropdown-menu-end">
					<a class="dropdown-item" href="{{ route("user.show", auth()->id())}}"><i class="align-middle me-1" data-feather="user"></i> My Profile</a>
					<div class="dropdown-divider"></div>
					<!-- Authentication -->
					<form method="POST" action="{{ route('logout') }}">
						@csrf

						<x-dropdown-link :href="route('logout')"
								onclick="event.preventDefault();
											this.closest('form').submit();">
							{{ __('Log Out') }}
						</x-dropdown-link>
					</form>
				</div>
			</li>
		</ul>
	</div>
</nav>